"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['../pysrc/gui/main_window.py']
DATA_FILES = []
OPTIONS = {
           'argv_emulation': True,
           'iconfile' : 'SelectiveIllu.icns',
           'packages': ['PIL', 'skimage', 'numpy', 'scipy']}

setup(
    app=APP,
    name="Selective Illumination",
    version="1.0",
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
